### ISSUE TITLE
robokassa

### ISSUE THREAD

**Issue by geepis** [OpenGamePanel/Module-Simple-billing#12]
The client enters the amount of replenishment of the account it throws to the ROBOKASSA service the Client chooses a convenient payment method and pays for it. On my email comes a notification of receipt of funds to my account also receive money Surprised the client does not see his money in his account and the server is not installed

**Comment by Zorrototo** [comment]
As far as I know nobody supports this module. It is an old legacy module. Very little chance to see any change to this module to fix the potential issues. Maybe I'm wrong but you better use the WHMCS mod for OGP, this one is more recent, but needs the external WHMCS billing platform.

Also I'm not sure what your issue is.. Maybe make sure what you wrote really says what you mean, maybe get some help because it seems like a google translation.

**Comment by geepis** [comment]
**robokassa-ipn_errors.log**

[02-Oct-2019 18:22:02 Europe/Moscow] PHP Notice:  Undefined variable: cart_id in /var/www/html/modules/simple-billing/robokassa-ipn.php on line 88
[02-Oct-2019 18:22:02 Europe/Moscow] PHP Notice:  Undefined variable: cart_id in /var/www/html/modules/simple-billing/robokassa-ipn.php on line 92
[02-Oct-2019 18:22:02 Europe/Moscow] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/modules/simple-billing/robokassa-ipn.php on line 94
[02-Oct-2019 18:22:02 Europe/Moscow] PHP Notice:  Trying to get property of non-object in /var/www/html/includes/functions.php on line 358
[02-Oct-2019 18:22:02 Europe/Moscow] PHP Warning:  mb_strlen(): Unknown encoding &quot;&quot; in /var/www/html/includes/PHPMailer/class.phpmailer.php on line 2833
[02-Oct-2019 18:22:02 Europe/Moscow] PHP Warning:  mb_strlen(): Unknown encoding &quot;&quot; in /var/www/html/includes/PHPMailer/class.phpmailer.php on line 2868
[02-Oct-2019 18:22:02 Europe/Moscow] PHP Warning:  mb_strlen(): Unknown encoding &quot;&quot; in /var/www/html/includes/PHPMailer/class.phpmailer.php on line 2833
[02-Oct-2019 18:22:02 Europe/Moscow] PHP Warning:  mb_strlen(): Unknown encoding &quot;&quot; in /var/www/html/includes/PHPMailer/class.phpmailer.php on line 2868

**Comment by geepis** [comment]
$body = 'Amount	paid		: '.$out_summ."<br>".
			'CART ID			: '.$inv_id."<br>";

	
	// Here you can do whatever you want with the variables, for instance inserting or updating data into your Database

	$user_homes = $db->resultQuery( "SELECT * 
									 FROM OGP_DB_PREFIXbilling_carts AS cart
									 JOIN
									 OGP_DB_PREFIXbilling_orders AS orders  
									 ON 
									 orders.cart_id=cart.cart_id
									 WHERE cart.cart_id=".$db->realEscapeSingle($cart_id));

	$query = "UPDATE " . $table_prefix . "billing_carts
			  SET paid=1
			  WHERE cart_id=".$db->realEscapeSingle($cart_id);
					  
	foreach($user_homes as $user_home)
	{
		if($user_home['home_id'] != 0)
		{

**Comment by geepis** [comment]
I did not change anything in the code, only in the settings of the panel itself . 
**robokassa-ipn.php**
.
.
80. 	// Here you can do whatever you want with the variables, for instance inserting or updating data 81. into your Database
82.	$user_homes = $db->resultQuery( "SELECT * 
83.									 FROM OGP_DB_PREFIXbilling_carts AS cart
84.									 JOIN
85.									 OGP_DB_PREFIXbilling_orders AS orders  
86.									 ON 
87.									 orders.cart_id=cart.cart_id
88.									 WHERE cart.cart_id=".$db->realEscapeSingle($cart_id));
89.	$query = "UPDATE " . $table_prefix . "billing_carts
90.			  SET paid=1
91.			  WHERE cart_id=".$db->realEscapeSingle($cart_id);
92.					  
93.	foreach($user_homes as $user_home)
94.	{
95.		if($user_home['home_id'] != 0)
96.		{
.
.
**functions.php**
.
.
350. 		foreach ( $email_addresses as $address ) 
351.			{
352.					$mail->AddAddress($address);
353.				}
354.				$mail->SetFrom($panel_email,$panel_name);
355.				$mail->AddReplyTo($panel_email,$panel_name);
356.			}
.
.
**class.phpmailer.php**
.
.
.
2830.    public function hasMultiBytes($str)
2831.    {
2832.        if (function_exists('mb_strlen')) {
2833.            return (strlen($str) > mb_strlen($str, $this->CharSet));
2834.        } else { // Assume no multibytes (we can't handle without mbstring functions anyway)
2835.            return false;
2836.        }
2837.    }
.
.
.
2861.        $start = '=?' . $this->CharSet . '?B?';
2862.       $end = '?=';
2863.       $encoded = '';
2864.      if ($linebreak === null) {
2865.            $linebreak = $this->LE;
2866.        }
2867.
2868.        $mb_length = mb_strlen($str, $this->CharSet);
2869.        // Each line must have length <= 75, including $start and $end
2870.        $length = 75 - strlen($start) - strlen($end);
2871.        // Average multi-byte ratio
2872.        $ratio = $mb_length / strlen($str);
2873.        // Base64 has a 4:3 ratio
2874.        $avgLength = floor($length * $ratio * .75);
.
.
.
I will be glad of any help , I just started to learn php and it is difficult for me to understand what needs to be corrected here . debian 9 php version 7.0.33. I will be glad of any help

**Comment by own3mall** [comment]
Agreed, I fixed some minor issues recently, but this module really probably shouldn't be used, and I have no idea if it works properly.
