### ISSUE TITLE
PHP 8.1 issue

### ISSUE THREAD

**Issue by TheFrozenThr0ne** [OpenGamePanel/Module-Simple-billing#14]
Me running PHP 8.1. And i get the following page see screen.

When i'm removing following from the shop.php then i can see the page normal.

`array_multisort($service_name,
					$service_id,
					$home_cfg_id,
					$mod_cfg_id,
					$remote_server_id,
					$slot_max_qty,
					$slot_min_qty,
					$price_hourly,
					$price_monthly,
					$price_year,
					$description,
					$img_url,
					$ftp,
					$install_method,
					$manual_url,
					$access_rights, SORT_DESC, $services);`

![image](https://github.com/OpenGamePanel/Module-Simple-billing/assets/11060723/2d5f1c5d-9c78-47c4-98a0-376f0cc733e9)

**Comment by TheFrozenThr0ne** [comment]
Ah, changing array_multisort to just array fixes it so far. Not sure if that is correct.

**Comment by own3mall** [comment]
Fixed in:  https://github.com/OpenGamePanel/Module-Simple-billing/pull/15

Thanks for reporting.
